### ISSUE TITLE
Why we need to provide actionCreators in configuring dev tools.

### ISSUE THREAD

**Issue by nuhbye** [jhen0409/react-native-boilerplate#11]
Why do we need to mention actionCreators here:
https://github.com/jhen0409/react-native-boilerplate/blob/master/src/configureStore.js#L27

For me it is working without this as well.

Thanks
Kunal

**Comment by jhen0409** [comment]
This is optional for debug actions easier, see [Use action creators for Dispatcher](https://github.com/zalmoxisus/redux-devtools-extension/releases/tag/v2.4.0).
