### ISSUE TITLE
addListener is undefined

### ISSUE THREAD

**Issue by MrHazimAli** [jhen0409/react-native-boilerplate#21]
Hye, I really like this boilerplate but recenly when I clone and want try the default one, I get error addListener is undefined, Im not sure where it comes from

any idea how to fix this one ? @jhen0409

**Comment by Kerita** [comment]
me too!

**Comment by MrHazimAli** [comment]
@Kerita , this is due to changes in react-navigation.. you need to check latest react-navigation documentation.. however, you also can use this boilerplate that I already clone and make some changes to what I need. 

I clone one of the branches and make changes that I need..
https://github.com/MrHazimAli/react-native-boilerplate

if I accidentally violates any copyright, let me know and I will delete the branch.
cc: @jhen0409

**Comment by cxk280** [comment]
@MrHazimAli: You should submit your fork as a pull request here. The old version of `react-navigation` that this repo currently uses is likely to cause more and more problems as time goes on. In my case, simply switching from a `StackNavigator` to a `SwitchNavigator` threw all kinds of unhelpful errors. Updating to a newer version of `react-navigation` was a nightmare, and I could not have done it without your fork. Many thanks!
