### ISSUE TITLE
Defs deprecated and/or uglify-js throwing error because of "window-size" module

### ISSUE THREAD

**Issue by ferologics** [jhen0409/react-native-boilerplate#5]
![screenshot 2016-04-21 13 54 04](https://cloud.githubusercontent.com/assets/5576161/14723992/990e7a1c-07c8-11e6-9496-9aed16dad836.png)

https://github.com/olov/defs

**Comment by jhen0409** [comment]
Thanks! :) I am also aware of the problem, it only in `npm run android` (with` react-native run-android`)

You can temporary use `npm start` in another tab, then run` npm run android`.

**Comment by ferologics** [comment]
I managed to get it working by

updating my npm
always using sudo with any commands involved
I had to "npm i --force"
and "npm update --force"

**Comment by jhen0409** [comment]
Yeah, it seems are problem of the older npm versions (I using v3.3), I tried second run of `npm install` it will be complete dependencies. The npm v3.8.x is work fine.

Keep this issue open. :)
