### ISSUE TITLE
How to build for production?

### ISSUE THREAD

**Issue by Winangel** [jhen0409/react-native-boilerplate#9]
I do not see any instruction on how to create a production ready application. 

The docs for react native mention a jslocation line to uncomment in the appDelegate.m file but this line is not present in a project generated using the rnb generator. 

Am I missing something?

**Comment by oroche** [comment]
Ok, Apparently this issue is not related to this project. In fact, the react-native docs seem out-of-date... the answer can be found [here](https://github.com/facebook/react-native/issues/8716).

**Comment by Winangel** [comment]
Ok, Apparently this issue is not related to this project. In fact, the react-native docs seem out-of-date... the answer can be found [here](https://github.com/facebook/react-native/issues/8716).

I'm closing this issue.
